version: '3.9'
services: 
  db:
    build:
      dockerfile: 'docker/postgres.dockerfile'
      context: ""
    
    image: rony/postgres
    container_name: postgres

    restart: always

    ports:
      - "5432:5432"
